### ISSUE TITLE
Remove import/prefer-default-export

### ISSUE THREAD

**Issue by ferrannp** [callstack/eslint-config-callstack-io#19]
It is quite annoying rule. I found myself lot of times defining constants and I want to use just `export`. I know that in the future there will be more. I am responsible enough to know how to export my files :D

**Comment by thymikee** [comment]
PR welcome!

**Comment by thymikee** [comment]
I'd also remove `import/first` because it makes it hard to separate module vs type imports:

```js
import Bar from 'bar-module';
import {foo} from './foo';

import type {Bar} from 'bar-module';
```
But that's unrelated to this issue.

**Comment by ferrannp** [comment]
What about Jest? I always like to do `jest.mock` first before any  `import`, but eslint does not really like it.

**Comment by thymikee** [comment]
I like my imports to be on top, `jest.mock` will be hoisted with `babel-jest` anyway. But since it's not mandatory, we can disable it too, not sure how though
